version: "3.4"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./accessibility-service/db/accessibility-db-initialize.sh:/docker-entrypoint-initdb.d/accessibility-db-initialize.sh
      - ./booking-service/db/booking-db-initialize.sh:/docker-entrypoint-initdb.d/booking-db-initialize.sh
      - ./management-service/db/management-db-initialize.sh:/docker-entrypoint-initdb.d/management-db-initialize.sh
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pg
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 8081:15672

  accessibility:
    image: accessibility
    build:
      context: .
      dockerfile: accessibility-service/Dockerfile
    ports:
      - "80:80"
    environment:
      - ConnectionStrings:Accessibility=Host=db;Database=postgres;Username=postgres;Password=pg

  booking:
    image: booking
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    ports:
      - "81:80"
    environment:
      - ConnectionStrings:Booking=Host=db;Database=booking;Username=postgres;Password=pg
      - RabbitMQ:Hostname=rabbit

  management:
    build:
      context: ./management-service
    volumes:
      - ./management-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 82:80
    environment:
      SERVER_PORT: 80
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: management
      MIGRATIONS_DIR: src/migrations
    depends_on:
      - db
    command: npm run start:dev

  employee-web-client:
    build:
      context: ./employee-web-client
    ports:
      - 3001:3001
    depends_on:
      - db
      - rabbit
      - adminer
      - accessibility
      - booking
      - management

volumes:
  pgdata:
