# debug postgres connection: https://dev.to/renanbr/controlling-service-readiness-in-docker-compose-4dfm
# https://docs.docker.com/compose/startup-order/

version: '3.7'

services:
  booking-app-management:
    container_name: booking-app-management
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: 4000
      POSTGRES_HOST: booking-app-management-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking-app-management
      MIGRATIONS_DIR: src/migrations
    networks:
      - webnet
    depends_on:
      - booking-app-management-postgres
#    command: npm run start:dev

  booking-app-management-postgres:
    container_name: booking-app-management-postgres
    image: postgres:12
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: booking-app-management
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:
volumes:
  pgdata:
